/**
 * RTF Reporting Tool – Value Assertion Evaluator
 *
 * Evaluates va:valueAssertion rules from the XBRL Formula Linkbase against
 * form data. Rules are loaded from value-rules.json (generated by
 * scripts/parse-value-assertions.mjs).
 *
 * Supported test patterns:
 *   - iaf:numeric-equal($a, iaf:sum(($b, [iaf:numeric-unary-minus($c), ...])))
 *   - $a >= 0 | $a <= 0 | $a <= 1 | $a >= $b | $a <= $b | $a = $b | $a != $b
 *   - $a = true() | $a = false()
 *   - $a = (xs:QName('ns:local'), ...)
 *   - matches($a, '^...$')
 *   - if (COND) then (RESULT) else (true())
 */

import fs from 'fs/promises';
import path from 'path';
import { logger } from '../lib/logger';

// ── Interfaces ────────────────────────────────────────────────────────────────

interface VariableBinding {
  row: string | null;
  col: string | null;
  fallbackValue: string | null;  // "0" | "()" | null
  dataType: string | null;       // mi1, si6, bi7, ei8, ...
}

export interface ValueAssertionRule {
  assertionId: string;
  template: string;
  test: string;
  globalCol: string | null;
  globalRow: string | null;
  variables: Record<string, VariableBinding>;
  errorMessage: string;
  pattern: 'iaf' | 'simple' | 'conditional' | 'regex' | 'unknown';
}

interface ValueRulesFile {
  version: string;
  generatedAt: string;
  rules: ValueAssertionRule[];
}

export interface AssertionViolation {
  assertionId: string;
  fieldKey: string;
  message: string;
  severity: 'error' | 'warning';
}

// ── Value resolution ──────────────────────────────────────────────────────────

type FormData = Record<string, unknown>;

/** Compute the cell key for a variable, merging variable-level and global filters */
function cellKey(
  varDef: VariableBinding,
  globalRow: string | null,
  globalCol: string | null
): string | null {
  const row = varDef.row ?? globalRow;
  const col = varDef.col ?? globalCol;
  if (row && col) return `${row}_${col}`;
  if (row) return row;
  if (col) return col;
  return null; // iterator – no specific coordinate
}

/** Resolve a variable's value from form data, applying fallback */
function resolveVar(
  varDef: VariableBinding,
  key: string | null,
  formData: FormData
): unknown {
  if (key === null) return undefined;
  const val = formData[key];
  if (val === undefined || val === null || val === '') {
    if (varDef.fallbackValue === '0') return 0;
    return undefined; // "()" = empty sequence
  }
  return val;
}

/** Coerce a value to number; returns NaN if not possible */
function toNum(v: unknown): number {
  if (typeof v === 'number') return v;
  if (typeof v === 'string') {
    const n = parseFloat(v.replace(',', '.'));
    return isNaN(n) ? NaN : n;
  }
  return NaN;
}

/** Check whether a value is "present" (not undefined/null/empty) */
function exists(v: unknown): boolean {
  return v !== undefined && v !== null && v !== '';
}

/** Parse QName local parts from xs:QName('ns:local') sequences */
function parseQNameList(expr: string): string[] {
  const names: string[] = [];
  const re = /xs:QName\('([^']+)'\)/g;
  let m;
  while ((m = re.exec(expr)) !== null) {
    const parts = m[1].split(':');
    names.push(parts[parts.length - 1]); // local name only: x01, x02, ...
  }
  return names;
}

// ── IAF arithmetic evaluator ──────────────────────────────────────────────────

/**
 * Evaluates:
 *   iaf:numeric-equal($a, iaf:sum(($b, [iaf:numeric-unary-minus($c), ] $d, ...)))
 *   iaf:numeric-equal($a, iaf:sum(($b, $c)))
 * Returns true if the equality holds (within floating-point tolerance).
 */
function evalIaf(test: string, vars: Record<string, unknown>): boolean | null {
  // Extract: iaf:numeric-equal( LHS , REST )
  const outer = /^iaf:numeric-equal\(\s*(\$\w+)\s*,\s*(.*)\)\s*$/.exec(test);
  if (!outer) return null;

  const lhsName = outer[1].slice(1); // strip $
  const rhsExpr = outer[2].trim();

  const lhsVal = toNum(vars[lhsName]);
  if (isNaN(lhsVal)) return true; // can't evaluate if LHS missing

  // Expect iaf:sum((...))
  const sumMatch = /^iaf:sum\(\s*\((.*)\)\s*\)\s*$/.exec(rhsExpr);
  if (!sumMatch) return null;

  const sumContent = sumMatch[1];
  let rhs = 0;

  // Parse sum items: $var or iaf:numeric-unary-minus($var) or iaf:sum($var)
  // Split on top-level commas
  const items = splitTopLevel(sumContent, ',');

  for (const item of items) {
    const t = item.trim();
    const negMatch = /^iaf:numeric-unary-minus\(\s*(\$\w+)\s*\)$/.exec(t);
    const innerSumMatch = /^iaf:sum\(\s*(\$\w+)\s*\)$/.exec(t);
    const varMatch = /^(\$\w+)$/.exec(t);

    if (negMatch) {
      const v = toNum(vars[negMatch[1].slice(1)]);
      rhs -= isNaN(v) ? 0 : v;
    } else if (innerSumMatch) {
      const v = toNum(vars[innerSumMatch[1].slice(1)]);
      rhs += isNaN(v) ? 0 : v;
    } else if (varMatch) {
      const v = toNum(vars[varMatch[1].slice(1)]);
      rhs += isNaN(v) ? 0 : v;
    }
    // Unknown item → skip (treat as 0)
  }

  // Tolerance: 0.5 unit (handles rounding in monetary values)
  return Math.abs(lhsVal - rhs) <= 0.5;
}

/** Split a string on a delimiter, respecting nested parentheses */
function splitTopLevel(s: string, delim: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = '';
  for (const ch of s) {
    if (ch === '(') depth++;
    else if (ch === ')') depth--;
    if (ch === delim && depth === 0) {
      parts.push(current);
      current = '';
    } else {
      current += ch;
    }
  }
  if (current) parts.push(current);
  return parts;
}

// ── Simple expression evaluator ───────────────────────────────────────────────

function evalSimple(test: string, vars: Record<string, unknown>): boolean | null {
  const t = test.trim();

  // $a = (xs:QName(...), ...) – enum check
  const enumMatch = /^(\$\w+)\s*=\s*\((.*xs:QName.*)\)$/.exec(t);
  if (enumMatch) {
    const val = vars[enumMatch[1].slice(1)];
    if (!exists(val)) return true; // field absent – not an enum error
    const allowed = parseQNameList(enumMatch[2]);
    return allowed.length === 0 || allowed.includes(String(val));
  }

  // $a = xs:QName('ns:local') – single enum value
  const singleQname = /^(\$\w+)\s*=\s*xs:QName\('([^']+)'\)$/.exec(t);
  if (singleQname) {
    const val = vars[singleQname[1].slice(1)];
    if (!exists(val)) return true;
    const local = singleQname[2].split(':').pop()!;
    return String(val) === local;
  }

  // $a = true() / $a = false()
  const boolMatch = /^(\$\w+)\s*=\s*(true|false)\(\)$/.exec(t);
  if (boolMatch) {
    const val = vars[boolMatch[1].slice(1)];
    const expected = boolMatch[2] === 'true';
    if (!exists(val)) return true;
    return Boolean(val) === expected;
  }

  // $a op $b – variable vs variable
  const varVarMatch = /^(\$\w+)\s*([><=!]+)\s*(\$\w+)$/.exec(t);
  if (varVarMatch) {
    const a = toNum(vars[varVarMatch[1].slice(1)]);
    const b = toNum(vars[varVarMatch[3].slice(1)]);
    if (isNaN(a) || isNaN(b)) return true;
    return evalNumOp(a, varVarMatch[2], b);
  }

  // $a op number
  const varNumMatch = /^(\$\w+)\s*([><=!]+)\s*(-?\d+(?:\.\d+)?)$/.exec(t);
  if (varNumMatch) {
    const a = toNum(vars[varNumMatch[1].slice(1)]);
    const b = parseFloat(varNumMatch[3]);
    if (isNaN(a)) return true;
    return evalNumOp(a, varNumMatch[2], b);
  }

  return null; // not handled
}

function evalNumOp(a: number, op: string, b: number): boolean {
  switch (op.trim()) {
    case '>=': return a >= b;
    case '<=': return a <= b;
    case '>': return a > b;
    case '<': return a < b;
    case '=': return Math.abs(a - b) <= 0.5;
    case '!=': return a !== b;
    default: return true;
  }
}

// ── Regex evaluator ───────────────────────────────────────────────────────────

function evalRegex(test: string, vars: Record<string, unknown>): boolean | null {
  const m = /^matches\(\s*(\$\w+)\s*,\s*'([^']*)'\s*\)$/.exec(test.trim());
  if (!m) return null;
  const val = vars[m[1].slice(1)];
  if (!exists(val)) return true;
  try {
    return new RegExp(m[2]).test(String(val));
  } catch {
    return true; // invalid regex – skip
  }
}

// ── Conditional evaluator ────────────────────────────────────────────────────

/**
 * Evaluates: if (COND) then (RESULT) else (true())
 * The else branch is always true(), so we only need to check COND → RESULT.
 */
function evalConditional(test: string, vars: Record<string, unknown>): boolean | null {
  // Extract COND and RESULT from "if (COND) then (RESULT) else (true())"
  const m = /^if\s*\((.+)\)\s*then\s*\((.+)\)\s*else\s*\(\s*true\(\)\s*\)\s*$/.exec(
    test.trim()
  );
  if (!m) return null;

  const condStr = m[1].trim();
  const resultStr = m[2].trim();

  const condVal = evalCondition(condStr, vars);
  if (condVal === null) return null; // unsupported condition

  if (!condVal) return true; // condition false → else branch (always true)

  // Condition is true → evaluate result
  const resultVal = evalResult(resultStr, vars);
  return resultVal;
}

/** Evaluate a condition expression → boolean */
function evalCondition(cond: string, vars: Record<string, unknown>): boolean | null {
  const c = cond.trim();

  // exists($a) or exists($b)
  const orExists = /^exists\((\$\w+)\)\s+or\s+exists\((\$\w+)\)$/.exec(c);
  if (orExists) {
    return exists(vars[orExists[1].slice(1)]) || exists(vars[orExists[2].slice(1)]);
  }

  // (exists($a)) and ($a >= 0) | (exists($a)) and ($a <= 0)
  const existsAndSign =
    /^\(\s*exists\((\$\w+)\)\s*\)\s+and\s+\(\s*(\$\w+)\s*([><=]+)\s*(0)\s*\)$/.exec(c);
  if (existsAndSign) {
    const varA = vars[existsAndSign[1].slice(1)];
    const varB = vars[existsAndSign[2].slice(1)];
    if (!exists(varA)) return false;
    const n = toNum(varB);
    if (isNaN(n)) return false;
    return evalNumOp(n, existsAndSign[3], parseFloat(existsAndSign[4]));
  }

  // (empty($a)) and ($b >= 0) | (empty($a)) and ($b <= 0)
  const emptyAndSign =
    /^\(\s*empty\((\$\w+)\)\s*\)\s+and\s+\(\s*(\$\w+)\s*([><=]+)\s*(0)\s*\)$/.exec(c);
  if (emptyAndSign) {
    const varA = vars[emptyAndSign[1].slice(1)];
    const varB = vars[emptyAndSign[2].slice(1)];
    if (exists(varA)) return false;
    const n = toNum(varB);
    if (isNaN(n)) return false;
    return evalNumOp(n, emptyAndSign[3], parseFloat(emptyAndSign[4]));
  }

  // exists($a)
  const existsSingle = /^exists\((\$\w+)\)$/.exec(c);
  if (existsSingle) {
    return exists(vars[existsSingle[1].slice(1)]);
  }

  // empty($a)
  const emptySingle = /^empty\((\$\w+)\)$/.exec(c);
  if (emptySingle) {
    return !exists(vars[emptySingle[1].slice(1)]);
  }

  // $a = true()
  const eqTrue = /^(\$\w+)\s*=\s*true\(\)$/.exec(c);
  if (eqTrue) {
    const val = vars[eqTrue[1].slice(1)];
    return exists(val) && Boolean(val) === true;
  }

  // $a = xs:QName('ns:local') and $b = xs:QName('ns:local')
  const doubleQname =
    /^(\$\w+)\s*=\s*xs:QName\('([^']+)'\)\s+and\s+(\$\w+)\s*=\s*xs:QName\('([^']+)'\)$/.exec(c);
  if (doubleQname) {
    const valA = vars[doubleQname[1].slice(1)];
    const valB = vars[doubleQname[3].slice(1)];
    const localA = doubleQname[2].split(':').pop()!;
    const localB = doubleQname[4].split(':').pop()!;
    return String(valA) === localA && String(valB) === localB;
  }

  // $a = xs:QName('ns:local')
  const singleQnameCond = /^(\$\w+)\s*=\s*xs:QName\('([^']+)'\)$/.exec(c);
  if (singleQnameCond) {
    const val = vars[singleQnameCond[1].slice(1)];
    if (!exists(val)) return false;
    const local = singleQnameCond[2].split(':').pop()!;
    return String(val) === local;
  }

  return null; // unsupported condition pattern
}

/** Evaluate a result expression (the "then" part) → boolean */
function evalResult(result: string, vars: Record<string, unknown>): boolean | null {
  const r = result.trim();

  // exists($c) and exists($d)
  const andExists = /^exists\((\$\w+)\)\s+and\s+exists\((\$\w+)\)$/.exec(r);
  if (andExists) {
    return exists(vars[andExists[1].slice(1)]) && exists(vars[andExists[2].slice(1)]);
  }

  // exists($b)
  const existsR = /^exists\((\$\w+)\)$/.exec(r);
  if (existsR) {
    return exists(vars[existsR[1].slice(1)]);
  }

  // $b = true()
  const eqTrue = /^(\$\w+)\s*=\s*true\(\)$/.exec(r);
  if (eqTrue) {
    const val = vars[eqTrue[1].slice(1)];
    return exists(val) && Boolean(val) === true;
  }

  // $b = false()
  const eqFalse = /^(\$\w+)\s*=\s*false\(\)$/.exec(r);
  if (eqFalse) {
    const val = vars[eqFalse[1].slice(1)];
    return !exists(val) || Boolean(val) === false;
  }

  // $b <= $a | $b >= $a (variable vs variable)
  const varVarR = /^(\$\w+)\s*([><=!]+)\s*(\$\w+)$/.exec(r);
  if (varVarR) {
    const a = toNum(vars[varVarR[1].slice(1)]);
    const b = toNum(vars[varVarR[3].slice(1)]);
    if (isNaN(a) || isNaN(b)) return true;
    return evalNumOp(a, varVarR[2], b);
  }

  // $b <= 0 | $b >= 0 (variable vs literal)
  const varNumR = /^(\$\w+)\s*([><=!]+)\s*(-?\d+(?:\.\d+)?)$/.exec(r);
  if (varNumR) {
    const a = toNum(vars[varNumR[1].slice(1)]);
    if (isNaN(a)) return true;
    return evalNumOp(a, varNumR[2], parseFloat(varNumR[3]));
  }

  // $c = (xs:QName(...), ...) – enum result
  const enumR = /^(\$\w+)\s*=\s*\((.*xs:QName.*)\)$/.exec(r);
  if (enumR) {
    const val = vars[enumR[1].slice(1)];
    if (!exists(val)) return false; // must be one of the enum values
    const allowed = parseQNameList(enumR[2]);
    return allowed.length === 0 || allowed.includes(String(val));
  }

  return null; // unsupported result pattern
}

// ── Main evaluator class ──────────────────────────────────────────────────────

export class ValueAssertionEvaluator {
  private rulesByTemplate: Map<string, ValueAssertionRule[]>;

  constructor(rules: ValueAssertionRule[]) {
    this.rulesByTemplate = new Map();
    for (const rule of rules) {
      const tmpl = rule.template.toUpperCase();
      const existing = this.rulesByTemplate.get(tmpl) ?? [];
      existing.push(rule);
      this.rulesByTemplate.set(tmpl, existing);
    }
    const total = rules.length;
    const templates = this.rulesByTemplate.size;
    logger.info(`ValueAssertionEvaluator: loaded ${total} rules for ${templates} templates`);
  }

  /** Return all templates that have value assertion rules */
  getTemplates(): string[] {
    return Array.from(this.rulesByTemplate.keys());
  }

  /**
   * Evaluate all value assertion rules for the given form template against formData.
   * The template is matched case-insensitively and also by prefix
   * (e.g. "RDP-BI" matches rules with template "RDP-BI").
   */
  evaluate(formCode: string, formData: FormData): AssertionViolation[] {
    const templateCode = formCode.toUpperCase();
    let rules = this.rulesByTemplate.get(templateCode);

    // Prefix fallback: "RDP-BI0" → template "RDP-BI"
    if (!rules) {
      for (const [tmpl, tmplRules] of this.rulesByTemplate) {
        if (templateCode.startsWith(tmpl)) {
          rules = tmplRules;
          break;
        }
      }
    }

    if (!rules || rules.length === 0) return [];

    const violations: AssertionViolation[] = [];

    for (const rule of rules) {
      try {
        const violation = this.evaluateRule(rule, formData);
        if (violation) violations.push(violation);
      } catch {
        // Rule evaluation error → skip silently
      }
    }

    return violations;
  }

  private evaluateRule(
    rule: ValueAssertionRule,
    formData: FormData
  ): AssertionViolation | null {
    // Resolve variable values
    const vars: Record<string, unknown> = {};
    let hasIterator = false;

    for (const [name, varDef] of Object.entries(rule.variables)) {
      const key = cellKey(varDef, rule.globalRow, rule.globalCol);
      if (key === null) {
        hasIterator = true;
        // For simple single-variable assertions with no key, try globalCol as key
        // (e.g. regex check on all cells in a column – unsupported in full)
        vars[name] = undefined;
      } else {
        vars[name] = resolveVar(varDef, key, formData);
      }
    }

    // Skip iterator-only assertions (need full XBRL engine iteration)
    if (hasIterator && Object.values(vars).every(v => v === undefined)) {
      return null;
    }

    const result = this.evalTest(rule.test, vars, rule.pattern);

    if (result === false) {
      // Determine the primary affected field (first variable with a key)
      const primaryField = this.primaryField(rule);
      return {
        assertionId: rule.assertionId,
        fieldKey: primaryField,
        message: rule.errorMessage,
        severity: 'error',
      };
    }

    return null;
  }

  private evalTest(
    test: string,
    vars: Record<string, unknown>,
    pattern: string
  ): boolean | null {
    switch (pattern) {
      case 'iaf': {
        const r = evalIaf(test, vars);
        return r;
      }
      case 'simple': {
        const r = evalSimple(test, vars);
        return r;
      }
      case 'conditional': {
        const r = evalConditional(test, vars);
        return r;
      }
      case 'regex': {
        const r = evalRegex(test, vars);
        return r;
      }
      default:
        return null; // unknown → skip
    }
  }

  private primaryField(rule: ValueAssertionRule): string {
    // Use first variable that has coordinates
    for (const [, varDef] of Object.entries(rule.variables)) {
      const key = cellKey(varDef, rule.globalRow, rule.globalCol);
      if (key) return key;
    }
    return rule.assertionId;
  }

  // ── Static factory ───────────────────────────────────────────────────────────

  static async load(dataDir: string): Promise<ValueAssertionEvaluator> {
    const filePath = path.join(dataDir, 'value-rules.json');
    try {
      const raw = await fs.readFile(filePath, 'utf8');
      const data = JSON.parse(raw) as ValueRulesFile;
      return new ValueAssertionEvaluator(data.rules);
    } catch (err) {
      logger.warn(`ValueAssertionEvaluator: could not load ${filePath}: ${err}`);
      return new ValueAssertionEvaluator([]);
    }
  }
}
